# Explorations in Condensed Matter  by G. Vidal

All physical ground states of local Hamiltonians obey area law which was known around 1990. Tensor network(TN) was later established upon this.

As preparation, we will review some techniques that bring us to study entanglement in many-body ground states.

* Exact diagonalization (N<40)
* Free fermion formalism (N~1000)

In [1]:
import numpy as np

In [18]:
a=1
b=2.3
z= complex(np.random.rand(),np.random.rand())

In [19]:
z

(0.8512083538820534+0.9142692419379427j)

In [45]:
v=np.array([[1,2,3,4],])
v.shape

(1, 4)

In [40]:
np.transpose(v)

array([[1],
       [2],
       [3],
       [4]])

In [41]:
np.dot(v,np.transpose(v))

array([[30]])

In [42]:
np.matmul(np.transpose(v),v)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [49]:
M = np.random.rand(3,3)+np.random.rand(3,3)*1j

In [58]:
H = (M+np.transpose(np.conj(M)))/2

In [59]:
E,U = np.linalg.eig(H)

In [60]:
E

array([ 1.85682518+6.17648335e-17j,  0.35576651+2.61911066e-17j,
       -0.38928945-4.68921326e-18j])

In [61]:
U

array([[ 0.30974298+0.1122486j ,  0.84071287+0.j        ,
        -0.39235607+0.17526588j],
       [ 0.69256998+0.j        , -0.45794617-0.10086499j,
        -0.51649837-0.18354239j],
       [ 0.64046613-0.04011858j,  0.10426755+0.24988339j,
         0.71755154+0.j        ]])

### Kronecker Product

In [62]:
I = np.eye(2)

In [68]:
sigmaX = np.array([[0.,1],[1.,0]])
sigmaZ = np.array([[1.,0],[0.,-1]])

In [69]:
A = np.array([[1.,2],[3.,4]])

In [70]:
np.kron(I,A)

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [0., 0., 1., 2.],
       [0., 0., 3., 4.]])

### 1D Quantum Ising model for N =3 spins

$H = \sigma^{x}_{1}\otimes\sigma^{x}_{2}+\sigma^{x}_{2}\otimes\sigma^{x}_{3}+\sigma^{x}_{3}\otimes\sigma^{x}_{1}+h(\sigma^{z}_{1}+\sigma^{z}_{2}+\sigma^{z}_{3})$

In [71]:
H3_o = np.kron(np.kron(sigmaX,sigmaX),I)+np.kron(I,np.kron(sigmaX,sigmaX))+np.kron(sigmaX,np.kron(I,sigmaX))

In [72]:
H3_m = np.kron(sigmaZ,np.kron(I,I))+np.kron(I,np.kron(sigmaZ,I))+np.kron(I,np.kron(I,sigmaZ))

In [73]:
H3_ising = H3_o + H3_m

In [74]:
H3_ising

array([[ 3.,  0.,  0.,  1.,  0.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  0.,  1.,  0.,  0.,  1.],
       [ 0.,  1.,  1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  0.,  0., -1.,  0.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  1.,  0., -1.,  1.,  0.],
       [ 1.,  0.,  0.,  1.,  0.,  1., -1.,  0.],
       [ 0.,  1.,  1.,  0.,  1.,  0.,  0., -3.]])

In [75]:
E_3ising , U_3ising = np.linalg.eig(H3_ising)

# Lec.02 

## 0:00~29:00

### 1D Quantum Ising model for N spins

$H = -\sum_{n=1}^{N-1}\sigma^{x}_{n}\sigma^{x}_{n+1}-h\sum_{n=1}^{N}\sigma^{z}_{n}-\sigma^{x}_{N}\sigma^{x}_{1}$

where the last term is picked out from summation and serves as periodic boundary condition.

We can introduce two operators 
* Translation operator T such that $T|s_{1},s_{2},...,s_{N-1},s_{N}>=|s_{N},s_{1},...,s_{N-2},s_{N-1}>$
* Spin flip(Z2 symmetry) operator S = $\sigma^{z}_{1}\sigma^{z}_{2}...\sigma^{z}_{N-1}\sigma^{z}_{N}$

It can be shown that T, S and H commute with each other.

And we denote the eigenbasis that diaganalize these three operators by $|E_{\alpha},K_{\alpha},P_{\alpha}>$

$H|E_{\alpha},K_{\alpha},P_{\alpha}>=E_{\alpha}|E_{\alpha},K_{\alpha},P_{\alpha}> \\
T|E_{\alpha},K_{\alpha},P_{\alpha}>=e^{iK_{\alpha}}|E_{\alpha},K_{\alpha},P_{\alpha}> , -\pi<K_{\alpha}\leq\pi \\
S|E_{\alpha},K_{\alpha},P_{\alpha}> = (-1)^{P_{\alpha}}|E_{\alpha},K_{\alpha},P_{\alpha}> , P_{\alpha}=0,1$

### Some remarks on quantum phase transition

Low energy or long distance criticality are described by conformal field theory(CFT). We list some facts of relevance here.
* A CFT is completely specified by the conformal datas which identify a universality class of quantum phase transition. 
* A conformal data consists of a list of so-called "primary field" $\phi_{\alpha}$ which has conformal dimension $h_{\alpha}$ and $\bar{h}_{\alpha}$
* Scaling dimension $\Delta = h_{\alpha}+\bar{h}_{\alpha}$ and conformal spin $s_{c}=h_{\alpha}-\bar{h}_{\alpha}$ are two datas we'll extract from the 1D quantum Ising model(spin chain).
* The physical concept of these two datas is that in 2D spacetime two point(one is origin here) correlation $<\phi_{\alpha}(x,y)\phi_{\beta}(0,0)>$ is decaying scaled by distance and angle proportional to $\Delta$ and $s_{c}$ respectively.

For our 1D quantum ising model with periodic b.c., primary fields are identity I, spin $\sigma$ and energy density $\epsilon$, and with antiperiodic b.c., primary fields are disorder operator and two fermionic field. Each of these six primary fields, there are corresponding $\Delta$ and $s_{c}$. We can extract them from our example of spin chain.

The connection of spin chain to CFT are established by Cardy in 80's. We'll not dig into the detail but give the result we need here.

$E_{\alpha}=a+\frac{b}{N}(\Delta-\frac{c}{12})+o(\frac{1}{N}) \\
K_{\alpha}=\frac{2\pi}{N}s_{c}$

## 29:00 ~ 41:00

### Build the Hamiltonian for Quantum ising model of N spins

In [101]:
N = 10
h = 1.0
XX = np.kron(sigmaX,sigmaX)
H = -XX-h*(np.kron(sigmaZ,I)+np.kron(I,sigmaZ))  # Start from two spins 

In [102]:
# Concatenate the recent spin chain with an additional spin
# Such process involves additional XX and sigmaZ with that newly added spin.
for n in range(3,N+1):
    H = np.kron(H,I) - np.kron(np.eye(2**(n-2)),XX) - h*np.kron(np.eye(2**(n-1)),sigmaZ)
H = H - np.kron(sigmaX, np.kron(np.eye(2**(N-2)),sigmaX))    

In [104]:
H.shape

(1024, 1024)

## 41:00 ~

### Build the translation operator for Quantum ising model of N spins

In [ ]:
T = 

# Lec. 03

* 1. Use Monte Carlo sampling to compute partition function Z of 2D Ising model.
* 2. Use transfer matrix M to compute Z as $Z= tr(M^{L})$
* 3. Extract the CFT data of 2D Ising model.